### ISSUE TITLE
Do you have any code for processing the CIC-IDS-2017 dataset?

### ISSUE THREAD

**Issue by nuistcai** [Western-OC2-Lab/Intrusion-Detection-System-Using-CNN-and-Transfer-Learning#1]

**Comment by LiYangHart** [comment]
Code is the same. Just change the dataset name and the number of classes

**Comment by nuistcai** [comment]
Okay, thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li Yang, ***@***.***&gt;; 
发送时间: 2024年9月4日(星期三) 凌晨2:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Western-OC2-Lab/Intrusion-Detection-System-Using-CNN-and-Transfer-Learning] Do you have any code for processing the CIC-IDS-2017 dataset? (Issue #1)














 
Code is the same. Just change the dataset name and the number of classes

**Comment by gongwolf** [comment]
Hi, the same question: 
do you have the code for processing the CICIDS2017 Dataset? The paper mentioned that 20 features are selected, and 60 consecutive data points are used to transfer the data to images. 
I checked the cited paper MTH-IDS, https://github.com/Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning/blob/main/MTH_IDS_IoTJ.ipynb. The input data is flow-based. How is the timestamp got? 

Thanks so much. Looking forward to the reply.
